---
- name: Install ILM
  tags: ilm

  block:
    - name: Create namespace
      kubernetes.core.k8s:
        wait: true
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ app_namespace }}"
      tags:
        - ilm_namespace

    # all components are free these days, but keep this here for future reference
    # - name: Verify harbor credentials are defined
    #   ansible.builtin.assert:
    #     that:
    #       - docker.username is defined
    #       - docker.password is defined
    #     fail_msg: >
    #       "Credentials for private docker repository is required when installing Cryptosense Discovery Provider"
    #   when: ilm.cryptosenseDiscoveryProvider

    # in case invalid credentials this fails
    - name: Verify harbor credentials
      ansible.builtin.uri:
        url: 'https://harbor.3key.company/api/v2.0/users/current'
        user: "{{ docker.username }}"
        password: "{{ docker.password }}"
        method: GET
        force_basic_auth: true
        headers:
          accept: application/json
      when: (docker.username is defined) and (docker.password is defined)
      register: result
      tags:
        - ilm_secret

    # this will always overwrite target file and we are ignoring change
    - name: Create secret for harbor
      ansible.builtin.shell:
        cmd: >
          /var/lib/rancher/rke2/bin/kubectl create secret -n {{ app_namespace }}
          docker-registry {{ docker.secret }} --docker-server={{ docker.server }}
          --docker-username={{ docker.username }} --docker-password={{ docker.password }}
          --docker-email={{ docker.email }} --dry-run='client' -o yaml > /root/install/docker-secret.yaml
      changed_when: false
      when: (docker.username is defined) and (docker.password is defined)
      tags:
        - ilm_secret

    # this apply only when changed - there must be more elegant way, but
    # problem with dockerconfigjson is that thre is 2 times base64 encoded
    # password
    #
    - name: Register secret for harbor
      kubernetes.core.k8s:
        namespace: "{{ app_namespace }}"
        state: present
        src: /root/install/docker-secret.yaml
      when: (docker.username is defined) and (docker.password is defined)
      tags:
        - ilm_secret

    - name: Create ingress-tls
      ansible.builtin.template:
        src: "ingress-tls.yaml.j2"
        dest: "/root/install/ingress-tls.yaml"
        owner: "{{ appliance_user }}"
        group: "{{ appliance_group }}"
        mode: '0644'
      when: (ingress is defined) and (ingress.certificate_file is defined) and (ingress.private_key_file is defined)
      tags:
        - ilm_ingress_tls

    - name: Register ingress-tls
      kubernetes.core.k8s:
        namespace: "{{ app_namespace }}"
        state: present
        src: "/root/install/ingress-tls.yaml"
      when: (ingress is defined) and (ingress.certificate_file is defined) and (ingress.private_key_file is defined)
      tags:
        - ilm_ingress_tls

    - name: Create schema for KeyCloak
      become: true
      become_user: postgres
      community.postgresql.postgresql_schema:
        name: keycloak
        owner: "{{ postgres.username | default('ilmuser') }}"
        database: "{{ postgres.database | default('ilmdb') }}"
      when:
        (ilm.keycloak is defined) and ilm.keycloak
      tags:
        - ilm_keycloak_schema

    - name: Copy local customized values.yaml file
      ansible.builtin.template:
        src: "ilm-values.local.yaml.j2"
        dest: "/root/install/values.local.yaml"
        mode: "0664"
      tags:
        - ilm_values
        - ilm_values_local

    - name: Check for custom values.custom.yaml
      ansible.builtin.stat:
        path: /home/{{ appliance_user }}/values.custom.yaml
      register:
        custom_file
      tags:
        - ilm_values

    - name: Define value files for helm instalation
      ansible.builtin.set_fact:
        values_files:
          - '/root/install/values.local.yaml'
          - "{{ custom_file.stat.path | default('/dev/null') }}"
      tags:
        - ilm_values

    - name: Install
      kubernetes.core.helm:
        timeout: 20m
        release_namespace: "{{ app_namespace }}"
        release_name: "{{ app_release_name }}"
        chart_ref: oci://harbor.3key.company/czertainly-helm/czertainly
        chart_version: "{{ ilm.version }}"
        wait: true
        values_files: "{{ values_files }}"
      tags:
        - ilm_install
